part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const SPLASH = _Paths.SPLASH;
  static const LOGIN = _Paths.LOGIN;
  static const REGISTER = _Paths.REGISTER;
  static const Two_Factor_Verification = _Paths.Two_Factor_Verification;
  static const EMAIL_VERIFICATION_OTP = _Paths.EMAIL_VERIFICATION_OTP;
  static const TWO_FACTOR_SUCCESS = _Paths.TWO_FACTOR_SUCCESS;
  static const ONBOARDING = _Paths.ONBOARDING;
  static const TRAINER_ONBOARDING = _Paths.TRAINER_ONBOARDING;
  static const ICON_CHAT = _Paths.ICON_CHAT;
  static const PROFILE_CREATE_ANIMATION = _Paths.PROFILE_CREATE_ANIMATION;
  static const ACTIVITY_TRACKER = _Paths.HOME + _Paths.ACTIVITY_TRACKER;
  static const TRAINEE_ONBOARDING = _Paths.TRAINEE_ONBOARDING;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const FITNESS_REPORT = _Paths.FITNESS_REPORT;
  static const FITNESS_REPORT_GENERATING = _Paths.FITNESS_REPORT_GENERATING;
  static const TRAINEE_FITNESS_REPORT_GENERATION =
      _Paths.TRAINEE_FITNESS_REPORT_GENERATION;
  static const OTP_VALIDATION = _Paths.OTP_VALIDATION;
  static const ICON_PROFILE = _Paths.ICON_PROFILE;
  static const FULL_BODY_TRACKER = _Paths.FULL_BODY_TRACKER;
  static const TRAINEE_REGISTER = _Paths.TRAINEE_REGISTER;
  static const WEEKLY_ROUTINE = _Paths.WEEKLY_ROUTINE;
  static const ADD_EXERCISE_TO_ROUTINE = _Paths.ADD_EXERCISE_TO_ROUTINE;
  static const EXPLORE = _Paths.EXPLORE;
  static const WORKOUT_HISTORY = _Paths.WORKOUT_HISTORY;
  static const WORKOUT_LOGGER = _Paths.WORKOUT_LOGGER;
  static const LOG_SET = _Paths.LOG_SET;
  static const LOG_CARDIO = _Paths.LOG_CARDIO;
  static const LOG_REPAIR = _Paths.LOG_REPAIR;
  static const PROGRAM_LIST = _Paths.PROGRAM_LIST;
  static const EXERCISE_LIBRARY = _Paths.EXERCISE_LIBRARY;
  static const EQUIPMENT_SELECTOR = _Paths.EQUIPMENT_SELECTOR;
  static const MUSCLE_SELECTOR = _Paths.MUSCLE_SELECTOR;
  static const CREATE_EXERCISE = _Paths.CREATE_EXERCISE;
  static const EXERCISE_REORDER = _Paths.EXERCISE_REORDER;
  static const WORKOUT_SETTINGS = _Paths.WORKOUT_SETTINGS;
  static const WORKOUT_SUMMARY = _Paths.WORKOUT_SUMMARY;
  static const WORKOUT_CELEBRATION = _Paths.WORKOUT_CELEBRATION;
  static const LIVE_ACTIVITY = _Paths.LIVE_ACTIVITY;
  static const CARDIO_SUMMARY = _Paths.CARDIO_SUMMARY;
  static const EXERCISE_DETAIL = _Paths.EXERCISE_DETAIL;
  static const SAVE_ACTIVITY = _Paths.SAVE_ACTIVITY;
  static const CARDIO_SELECTOR = _Paths.CARDIO_SELECTOR;
  static const RUN_TRACKER = _Paths.RUN_TRACKER;
  static const PROGRAM_DETAIL = _Paths.PROGRAM_DETAIL;
  static const GOAL_TRACKING = _Paths.GOAL_TRACKING;
  static const YOUR_ACTIVITY_GOALS = _Paths.YOUR_ACTIVITY_GOALS;
  static const YOUR_RECOVERY_GOALS = _Paths.YOUR_RECOVERY_GOALS;
  static const YOUR_NUTRITION_GOALS = _Paths.YOUR_NUTRITION_GOALS;
  static const YOUR_DAILY_GOALS = _Paths.YOUR_DAILY_GOALS;
  static const TRAINEE_ONBOARDING_BY_PAGE = _Paths.TRAINEE_ONBOARDING_BY_PAGE;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const SPLASH = '/splash';
  static const LOGIN = '/login';
  static const REGISTER = '/register';
  static const Two_Factor_Verification = '/two-factor-verification';
  static const EMAIL_VERIFICATION_OTP = '/email-verification-otp';
  static const TWO_FACTOR_SUCCESS = '/two-factor-success';
  static const ONBOARDING = '/onboarding';
  static const TRAINER_ONBOARDING = '/trainer-onboarding';
  static const PROFILE_CREATE_ANIMATION = '/profile-create-animation';
  static const ACTIVITY_TRACKER = '/activity-tracker';
  static const ICON_CHAT = '/icon-chat';
  static const TRAINEE_ONBOARDING = '/trainee-onboarding';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const FITNESS_REPORT = '/fitness-report';
  static const FITNESS_REPORT_GENERATING = '/fitness-report-generating';
  static const TRAINEE_FITNESS_REPORT_GENERATION =
      '/trainee-fitness-report-generation';
  static const OTP_VALIDATION = '/otp-validation';
  static const ICON_PROFILE = '/icon-profile';
  static const FULL_BODY_TRACKER = '/full-body-tracker';
  static const TRAINEE_REGISTER = '/trainee-register';
  static const WEEKLY_ROUTINE = '/weekly-routine';
  static const ADD_EXERCISE_TO_ROUTINE = '/add-exercise-to-routine';
  static const EXPLORE = '/explore';
  static const WORKOUT_HISTORY = '/workout-history';
  static const WORKOUT_LOGGER = '/workout-logger';
  static const LOG_SET = '/log-set';
  static const LOG_CARDIO = '/log-cardio';
  static const LOG_REPAIR = '/log-repair';
  static const PROGRAM_LIST = '/program-list';
  static const EXERCISE_LIBRARY = '/exercise-library';
  static const EQUIPMENT_SELECTOR = '/equipment-selector';
  static const MUSCLE_SELECTOR = '/muscle-selector';
  static const CREATE_EXERCISE = '/create-exercise';
  static const EXERCISE_REORDER = '/exercise-reorder';
  static const WORKOUT_SETTINGS = '/workout-settings';
  static const WORKOUT_SUMMARY = '/workout-summary';
  static const WORKOUT_CELEBRATION = '/workout-celebration';
  static const LIVE_ACTIVITY = '/live-activity';
  static const CARDIO_SUMMARY = '/cardio-summary';
  static const EXERCISE_DETAIL = '/exercise-detail';
  static const SAVE_ACTIVITY = '/save-activity';
  static const CARDIO_SELECTOR = '/cardio-selector';
  static const RUN_TRACKER = '/run-tracker';
  static const PROGRAM_DETAIL = '/program-detail';
  static const GOAL_TRACKING = '/goal-tracking';
  static const YOUR_ACTIVITY_GOALS = '/your-activity-goals';
  static const YOUR_RECOVERY_GOALS = '/your-recovery-goals';
  static const YOUR_NUTRITION_GOALS = '/your-nutrition-goals';
  static const YOUR_DAILY_GOALS = '/your-daily-goals';
  static const TRAINEE_ONBOARDING_BY_PAGE = '/trainee-onboarding-by-page';
}
